apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
replacements:
- path: ../../_transforms/name-from-repo.yaml
patchesJson6902:
- path: source.yaml
  target:
    kind: GitRepository
    name: stack
- path: inputs.yaml
  target:
    kind: Terraform
    name: stack
# not possible without dependency support in terraform controller
# - path: dependencies.yaml
#   target:
#     kind: Terraform
#     name: stack
